### ISSUE TITLE
domain.enter is not a function 

### ISSUE THREAD

**Issue by B0F1B0** [mrbungle64/ioBroker.ecovacs-deebot#10]
ich habe einen Ecovacs Deebot 950 und habe den iobroker-adapter Ecovacs Deebot 0.3.7 (auch bei 0.3.5 und 0.3.6) installiert und bekomme die folgende Fehlermeldung:

host.pi | 2020-02-15 18:40:15.748 | info | Restart adapter system.adapter.ecovacs-deebot.0 because enabled
-- | -- | -- | --
host.pi | 2020-02-15 18:40:15.747 | info | instance system.adapter.ecovacs-deebot.0 terminated with code 0 (NO_ERROR)
host.pi | 2020-02-15 18:40:15.747 | error | Caught by controller[1]: at Writable.write (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/readable-stream/lib/_stream_writable.js:334:11)
host.pi | 2020-02-15 18:40:15.746 | error | Caught by controller[1]: at writeOrBuffer (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/readable-stream/lib/_stream_writable.js:417:5)
host.pi | 2020-02-15 18:40:15.745 | error | Caught by controller[1]: at doWrite (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/readable-stream/lib/_stream_writable.js:428:64)
host.pi | 2020-02-15 18:40:15.744 | error | Caught by controller[1]: at Writable.writable._write (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:294:5)
host.pi | 2020-02-15 18:40:15.744 | error | Caught by controller[1]: at work (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:283:12)
host.pi | 2020-02-15 18:40:15.743 | error | Caught by controller[1]: at MqttClient._handlePacket (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:358:12)
host.pi | 2020-02-15 18:40:15.742 | error | Caught by controller[1]: at MqttClient._handleAck (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:1249:7)
host.pi | 2020-02-15 18:40:15.742 | error | Caught by controller[1]: at cb (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:634:7)
host.pi | 2020-02-15 18:40:15.741 | error | Caught by controller[1]: at subscribe (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:73:33)
host.pi | 2020-02-15 18:40:15.740 | error | Caught by controller[1]: at EcovacsMQTT.emit (events.js:199:12)
host.pi | 2020-02-15 18:40:15.739 | error | Caught by controller[1]: TypeError: domain.enter is not a function
host.pi | 2020-02-15 18:40:15.737 | error | Caught by controller[0]: [EcovacsAPI] Failure code 0002
ecovacs-deebot.0 | 2020-02-15 18:40:15.191 | info | (2045) Terminated (NO_ERROR): Without reason
ecovacs-deebot.0 | 2020-02-15 18:40:15.189 | info | (2045) terminating
ecovacs-deebot.0 | 2020-02-15 18:40:15.170 | info | (2045) cleaned everything up...
ecovacs-deebot.0 | 2020-02-15 18:40:15.166 | error | (2045) TypeError: domain.enter is not a function at EcovacsMQTT.emit (events.js:199:12) at subscribe (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/eco
ecovacs-deebot.0 | 2020-02-15 18:40:15.163 | error | (2045) uncaught exception: domain.enter is not a function
ecovacs-deebot.0 | 2020-02-15 18:40:13.132 | info | (2045) Successfully connected to Ecovacs server

`uname -a`
`Linux pi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux`

Node.js: v8.16.0 
NPM: 6.4.1

@mrbungle64 @all wenn ihr etwas weiteres benötigt (logs / testing) gibt mir bitte bescheid

""THERE WE HAVE THE SALAD""

B0F1B0

**Comment by B0F1B0** [comment]
der Error lag am einer zu alten Node.JS Version (8.3)

hier die Anleitung wie man Node.JS für den Iobroker Updatet. 

https://forum.iobroker.net/topic/22867/how-to-node-js-f%C3%BCr-iobroker-richtig-updaten

Zur Info: Mein Zigbee Adapter hat nach dem Node.JS Update nicht mehr funktioniert.

""THERE WE HAVE THE SALAD""

B0F1B0
