### ISSUE TITLE
Errors  and warns after updating

### ISSUE THREAD

**Issue by Pittini** [mrbungle64/ioBroker.ecovacs-deebot#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Maybe nothing interesting, but since some updates yesterday, i got the following errors:

<html>
<body>

ecovacs-deebot.0 | 2021-08-09 13:17:47.951 | warn | Error message received: RequestOAuthError: Authentication error
-- | -- | -- | --
ecovacs-deebot.0 | 2021-08-09 13:17:47.951 | warn | Error message received: RequestOAuthError: Authentication error
ecovacs-deebot.0 | 2021-08-09 13:17:47.950 | warn | Error message received: RequestOAuthError: Authentication error
ecovacs-deebot.0 | 2021-08-09 13:17:47.950 | warn | Error message received: RequestOAuthError: Authentication error
ecovacs-deebot.0 | 2021-08-09 13:17:47.949 | warn | Error message received: RequestOAuthError: Authentication error
ecovacs-deebot.0 | 2021-08-09 13:17:47.949 | warn | Error message received: RequestOAuthError: Authentication error
ecovacs-deebot.0 | 2021-08-09 13:17:47.945 | warn | Received disconnect event from library
ecovacs-deebot.0 | 2021-08-09 13:17:47.944 | warn | Received disconnect event from library
ecovacs-deebot.0 | 2021-08-09 13:17:47.944 | warn | Received disconnect event from library
ecovacs-deebot.0 | 2021-08-09 13:17:47.944 | warn | Received disconnect event from library
ecovacs-deebot.0 | 2021-08-09 13:17:47.944 | warn | Received disconnect event from library
ecovacs-deebot.0 | 2021-08-09 13:17:47.943 | error | Received disconnect event from library

</body>
</html>

### With which model does the problem occur?

Deebot OZMO 950

### From which source you have installed the adapter?

Beta (latest)

### Which version of the ioBroker adapter are you using?

1.2.1

### Which version of the ioBroker adapter are you using?

???

### Which version of ioBroker / JS controller you have installed?

5.2.8

### Which version of Node.js are you using?

12.18.4

**Comment by mrbungle64** [comment]
@Pittini

Have you already restarted the adapter instance?

> but since some updates yesterday

What do you mean with "some updates". Please specify what updates you mean

> From which source you have installed the adapter?
> Beta (latest)
> Which version of the ioBroker adapter are you using?
> 1.2.1

Are you really still using 1.2.1 from Beta (latest)? I released version 1.2.2 4 days ago.

**Comment by Pittini** [comment]
> @Pittini
> 
> Have you already restarted the adapter instance?

sure

> > but since some updates yesterday
> 
> What do you mean with "some updates". Please specify what updates you mean
> 
Sorry, impossible. I update every one or two weeks all necessary adapters to newest latest versions (after checking the changelog). I dont remember which one I've updated.

> > From which source you have installed the adapter?
> > Beta (latest)
> > Which version of the ioBroker adapter are you using?
> > 1.2.1
> 
> Are you really still using 1.2.1 from Beta (latest)? I released version 1.2.2 4 days ago.

Yes, i didnt update from 1.2.1 to 1.2.2 because the description was:
_"• Funktionalität zum Laden einer statischen Map für Modelle verfügbar gemacht (experimentell)"_
This dont interests me, so I didnt update this time.
> 
> > Which version of ioBroker / JS controller you have installed?
> > 5.2.8
> 
> This is not a valid version of JS controller. Please check again

Sorry, 3.3.14

**Comment by mrbungle64** [comment]
@Pittini 

ok, how often does the warning "Error message received: RequestOAuthError: Authentication error" occur?
Does the adapter instance work properly otherwise?

**Comment by mrbungle64** [comment]
@Pittini 

In [this case](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/127) the problems were caused by a firewall.
Are you maybe also using such components in your network?

**Comment by Pittini** [comment]
> ok, how often does the warning "Error message received: RequestOAuthError: Authentication error" occur?

once or twice a day

> Does the adapter instance work properly otherwise?

All functions I use are working properly, but i can not say everything is fine, because I dont use everything. The used Stats are shown properly, and the room control also. Here is what I use
![2021-08-09 17_13_52-vis](https://user-images.githubusercontent.com/51408942/128730032-289302f8-447c-451a-97d4-59f3d5c47cc8.png)

>In this case the problems were caused by a firewall.
>Are you maybe also using such components in your network?

Nothing special, just the Fritzbox 7590, and there are no changes the last month.

**Comment by mrbungle64** [comment]
@Pittini 

ok, thanks for the additional infos 👍🏻 

The "RequestOAuthError: Authentication error" error message is received by the Ecovacs API.

Originally that error occured when you're using multiple instances with multiple devices on the same server. But this issue is already fixed. I don't know why that still happens in certain circumstances, but it should not have any negative effects.
I also had this error at times as well. However, I haven't noticed that error for a while now.

I'll keep an eye on that and try to improve the handling of this type of error.
Please let me know if this happens more than 3 times a day or if you notice any other issues related to this.

**Comment by andre-bu** [comment]
Hab nach dem Update auf Admin 5.1.23 und js-controller 3.3.15 auch eine Menge Meldungen im LOG.

node: v12.20.2
js-controller: 3.3.15
Admin 5.1.23
Ecovacs Adapter 1.2.1
Deebot 950
"Stable"

2021-08-10 09:49:25.610 - info: web.0 (17491) State value to set for "ecovacs-deebot.0.control.spotArea_0" has to be type "boolean" but received type "string"
2021-08-10 09:58:42.261 - info: ecovacs-deebot.0 (16856) State value to set for "ecovacs-deebot.0.cleaninglog.totalTime" has to be type "number" but received type "string"
2021-08-10 09:58:42.287 - info: ecovacs-deebot.0 (16856) State value to set for "ecovacs-deebot.0.cleaninglog.totalTime" has to be type "number" but received type "string"
2021-08-10 09:58:45.182 - info: ecovacs-deebot.0 (16856) State value to set for "ecovacs-deebot.0.cleaninglog.lastCleaningTimestamp" has to be type "string" but received type "number"
2021-08-10 09:58:45.252 - info: ecovacs-deebot.0 (16856) State value to set for "ecovacs-deebot.0.cleaninglog.lastCleaningTimestamp" has to be type "string" but received type "number" 
2021-08-10 16:25:57.660 - warn: ecovacs-deebot.0 (16856) Error message received: Request Timeout
2021-08-10 16:25:57.662 - warn: ecovacs-deebot.0 (16856) Error message received: Request Timeout
2021-08-10 16:26:56.922 - warn: ecovacs-deebot.0 (16856) Error message received: Request Timeout
2021-08-10 16:26:56.923 - warn: ecovacs-deebot.0 (16856) Error message received: Request Timeout
2021-08-10 16:28:36.247 - error: ecovacs-deebot.0 (16856) uncaught exception: Connection refused: Server unavailable
2021-08-10 16:28:36.250 - error: ecovacs-deebot.0 (16856) Error: Connection refused: Server unavailable
at MqttClient._handleConnack (/opt/iobroker/node_modules/mqtt/lib/client.js:1190:15)
at MqttClient._handlePacket (/opt/iobroker/node_modules/mqtt/lib/client.js:424:12)
at work (/opt/iobroker/node_modules/mqtt/lib/client.js:321:12)
at Writable.writable._write (/opt/iobroker/node_modules/mqtt/lib/client.js:335:5)
at doWrite (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
at writeOrBuffer (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
at Writable.write (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
at TLSSocket.ondata (_stream_readable.js:718:22)
at TLSSocket.emit (events.js:314:20)
at addChunk (_stream_readable.js:297:12)
2021-08-10 16:28:36.251 - error: ecovacs-deebot.0 (16856) Exception-Code: 3: Connection refused: Server unavailable
2021-08-10 16:28:36.262 - info: ecovacs-deebot.0 (16856) cleaned everything up...
2021-08-10 16:28:36.263 - info: ecovacs-deebot.0 (16856) terminating
2021-08-10 16:28:36.265 - warn: ecovacs-deebot.0 (16856) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-08-10 16:28:36.981 - error: host.ioBkoker202 instance system.adapter.ecovacs-deebot.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-08-10 16:28:36.988 - info: host.ioBkoker202 Restart adapter system.adapter.ecovacs-deebot.0 because enabled
2021-08-10 16:29:07.051 - info: host.ioBkoker202 instance system.adapter.ecovacs-deebot.0 started with pid 26980
2021-08-10 16:29:08.989 - info: ecovacs-deebot.0 (26980) starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v12.20.2, js-controller: 3.3.15
2021-08-10 16:29:10.823 - info: ecovacs-deebot.0 (26980) Successfully connected to Ecovacs server
2021-08-10 16:29:10.826 - info: ecovacs-deebot.0 (26980) Number of devices: 1
2021-08-10 16:29:10.827 - info: ecovacs-deebot.0 (26980) Device[0]: {"did":"30e113b3-6737-4007-a5ea-2efb50e51823","name":"E0A412796B09HEZ50221","class":"yna5xi","resource":"Ja3s","nick":"Robocat","company":"eco-ng","bindTs":1609868337171,"service":{"jmq":"jmq-ngiot-eu.dc.ww.ecouser.net","mqs":"api-ngiot.dc-as.ww.ecouser.net"}}
2021-08-10 16:29:10.828 - info: ecovacs-deebot.0 (26980) Using device Device[0]
2021-08-10 16:29:54.485 - warn: husq-automower.0 (8111) Read-only state "husq-automower.0.mower.lastStatus" has been written without ack-flag with value "OK_CHARGING"
2021-08-10 16:29:54.486 - warn: husq-automower.0 (8111) Read-only state "husq-automower.0.mower.lastStatusTime" has been written without ack-flag with value "1628605727427"
2021-08-10 16:29:54.614 - warn: husq-automower.0 (8111) Read-only state "husq-automower.0.mower.homeLocation.currentDistance" has been written without ack-flag with value "11"
2021-08-10 16:29:58.233 - info: ecovacs-deebot.0 (26980) Robocat instance successfully connected
2021-08-10 16:29:58.238 - info: ecovacs-deebot.0 (26980) [vacbot] name: DEEBOT OZMO 950 Series
2021-08-10 16:38:08.327 - error: ecovacs-deebot.0 (26980) uncaught exception: Connection refused: Server unavailable
2021-08-10 16:38:08.331 - error: ecovacs-deebot.0 (26980) Error: Connection refused: Server unavailable
at MqttClient._handleConnack (/opt/iobroker/node_modules/mqtt/lib/client.js:1190:15)
at MqttClient._handlePacket (/opt/iobroker/node_modules/mqtt/lib/client.js:424:12)
at work (/opt/iobroker/node_modules/mqtt/lib/client.js:321:12)
at Writable.writable._write (/opt/iobroker/node_modules/mqtt/lib/client.js:335:5)
at doWrite (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
at writeOrBuffer (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
at Writable.write (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
at TLSSocket.ondata (_stream_readable.js:718:22)
at TLSSocket.emit (events.js:314:20)
at addChunk (_stream_readable.js:297:12)
2021-08-10 16:38:08.332 - error: ecovacs-deebot.0 (26980) Exception-Code: 3: Connection refused: Server unavailable
2021-08-10 16:38:08.341 - info: ecovacs-deebot.0 (26980) cleaned everything up...
2021-08-10 16:38:08.342 - info: ecovacs-deebot.0 (26980) terminating
2021-08-10 16:38:08.344 - warn: ecovacs-deebot.0 (26980) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-08-10 16:38:09.036 - error: host.ioBkoker202 instance system.adapter.ecovacs-deebot.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-08-10 16:38:09.043 - info: host.ioBkoker202 Restart adapter system.adapter.ecovacs-deebot.0 because enabled
2021-08-10 16:38:39.102 - info: host.ioBkoker202 instance system.adapter.ecovacs-deebot.0 started with pid 29358
2021-08-10 16:38:41.050 - info: ecovacs-deebot.0 (29358) starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v12.20.2, js-controller: 3.3.15
2021-08-10 16:38:42.262 - info: ecovacs-deebot.0 (29358) Successfully connected to Ecovacs server
2021-08-10 16:38:42.265 - info: ecovacs-deebot.0 (29358) Number of devices: 1
2021-08-10 16:38:42.266 - info: ecovacs-deebot.0 (29358) Device[0]: {"did":"30e113b3-6737-4007-a5ea-2efb50e51823","name":"E0A412796B09HEZ50221","class":"yna5xi","resource":"Ja3s","nick":"Robocat","company":"eco-ng","bindTs":1609868337171,"service":{"jmq":"jmq-ngiot-eu.dc.ww.ecouser.net","mqs":"api-ngiot.dc-as.ww.ecouser.net"}}
2021-08-10 16:38:42.266 - info: ecovacs-deebot.0 (29358) Using device Device[0]
2021-08-10 16:38:46.663 - error: ecovacs-deebot.0 (29358) uncaught exception: Connection refused: Server unavailable
2021-08-10 16:38:46.669 - error: ecovacs-deebot.0 (29358) Error: Connection refused: Server unavailable
at MqttClient._handleConnack (/opt/iobroker/node_modules/mqtt/lib/client.js:1190:15)
at MqttClient._handlePacket (/opt/iobroker/node_modules/mqtt/lib/client.js:424:12)
at work (/opt/iobroker/node_modules/mqtt/lib/client.js:321:12)
at Writable.writable._write (/opt/iobroker/node_modules/mqtt/lib/client.js:335:5)
at doWrite (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
at writeOrBuffer (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
at Writable.write (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
at TLSSocket.ondata (_stream_readable.js:718:22)
at TLSSocket.emit (events.js:314:20)
at addChunk (_stream_readable.js:297:12)
2021-08-10 16:38:46.670 - error: ecovacs-deebot.0 (29358) Exception-Code: 3: Connection refused: Server unavailable
2021-08-10 16:38:46.685 - info: ecovacs-deebot.0 (29358) cleaned everything up...
2021-08-10 16:38:46.686 - info: ecovacs-deebot.0 (29358) terminating
2021-08-10 16:38:46.688 - warn: ecovacs-deebot.0 (29358) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-08-10 16:38:47.337 - error: host.ioBkoker202 instance system.adapter.ecovacs-deebot.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-08-10 16:38:47.339 - info: host.ioBkoker202 Restart adapter system.adapter.ecovacs-deebot.0 because enabled
2021-08-10 16:38:47.339 - warn: host.ioBkoker202 Do not restart adapter system.adapter.ecovacs-deebot.0 because restart loop detected
2021-08-10 17:01:27.638 - info: ecovacs-deebot.0 (2432) starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v12.20.2, js-controller: 3.3.15
2021-08-10 17:01:28.481 - info: ecovacs-deebot.0 (2432) Successfully connected to Ecovacs server
2021-08-10 17:01:28.484 - info: ecovacs-deebot.0 (2432) Number of devices: 1
2021-08-10 17:01:28.485 - info: ecovacs-deebot.0 (2432) Device[0]: {"did":"30e113b3-6737-4007-a5ea-2efb50e51823","name":"E0A412796B09HEZ50221","class":"yna5xi","resource":"Ja3s","nick":"Robocat","company":"eco-ng","bindTs":1609868337171,"service":{"jmq":"jmq-ngiot-eu.dc.ww.ecouser.net","mqs":"api-ngiot.dc-as.ww.ecouser.net"}}
2021-08-10 17:01:28.486 - info: ecovacs-deebot.0 (2432) Using device Device[0]
2021-08-10 17:01:29.342 - info: ecovacs-deebot.0 (2432) Robocat instance successfully connected
2021-08-10 17:01:29.349 - info: ecovacs-deebot.0 (2432) [vacbot] name: DEEBOT OZMO 950 Series
2021-08-10 17:01:50.320 - warn: ecovacs-deebot.0 (2432) Error message received: Request Timeout
2021-08-10 17:02:44.291 - warn: ecovacs-deebot.0 (2432) Error message received: Request Timeout

**Comment by mrbungle64** [comment]
@andre-bu 

> 2021-08-10 09:49:25.610 - info: web.0 (17491) State value to set for "ecovacs-deebot.0.control.spotArea_0" has to be type "boolean" but received type "string"
> 2021-08-10 09:58:42.261 - info: ecovacs-deebot.0 (16856) State value to set for "ecovacs-deebot.0.cleaninglog.totalTime" has to be type "number" but received type "string"
> 2021-08-10 09:58:42.287 - info: ecovacs-deebot.0 (16856) State value to set for "ecovacs-deebot.0.cleaninglog.totalTime" has to be type "number" but received type "string"
> 2021-08-10 09:58:45.182 - info: ecovacs-deebot.0 (16856) State value to set for "ecovacs-deebot.0.cleaninglog.lastCleaningTimestamp" has to be type "string" but received type "number"
> 2021-08-10 09:58:45.252 - info: ecovacs-deebot.0 (16856) State value to set for "ecovacs-deebot.0.cleaninglog.lastCleaningTimestamp" has to be type "string" but received type "number"

Lösche mal bitte den `cleaninglog` Ordner. Die Datenpunkte sind wohl von einer älteren Version falsch angelegt worden. Die sollten dann wieder autom. neu erstellt werden.

> 2021-08-10 16:26:56.923 - warn: ecovacs-deebot.0 (16856) Error message received: Request Timeout
> 2021-08-10 16:28:36.247 - error: ecovacs-deebot.0 (16856) uncaught exception: Connection refused: Server unavailable
> 2021-08-10 16:28:36.250 - error: ecovacs-deebot.0 (16856) Error: Connection refused: Server unavailable
> 2021-08-10 16:28:36.251 - error: ecovacs-deebot.0 (16856) Exception-Code: 3: Connection refused: Server unavailable

Das sind alles Meldungen die auf ein Netzwerkproblem oder ein Problem bei den Ecovacs Servern hindeuten.
Besteht das Problem immer noch?

**Comment by mrbungle64** [comment]
@andre-bu 

Ich habe gerade gesehen, dass es bei mir zwischen 16:25 und 16:27 auch quasi die gleichen Fehlermeldungen gab.

Da gab es dann wohl wirklich Probleme auf Seite von den Ecovacs Servern.
Im Endeffekt sagen die Fehlermeldungen auch das aus: `Server unavailable`

**Comment by andre-bu** [comment]
Danke für die schnelle Rückmeldung.
Den Ordner lösche ich und gebe Rückmeldung.

Die Meldung Server nicht erreichbar war vermutlich wirklich "nur" ein
Netzwerk Problem. Das ist erst einmal wieder weg nachdem ich den Adapter
mal neu gestartet hatte.

Die Meldung warn: ecovacs-deebot.0 (16856) Error message received: Request
Timeout kommt aber weiterhin in regelmäßigen Abständen.

Sascha ***@***.***> schrieb am Di., 10. Aug. 2021, 21:00:

**Comment by andre-bu** [comment]
Das löschen des Ordners cleaninglog hat, so wie es aktuell aussieht, das Problem mit dem "state" behoben. Nach dem Neustart des Adapter wurde der Ordner neu angelegt und ich erhalte ich folgendes LOG

<html><body>


ecovacs-deebot.0 | 2021-08-10 21:17:38.621 | info | [vacbot] name: DEEBOT OZMO 950 Series
-- | -- | -- | --
ecovacs-deebot.0 | 2021-08-10 21:17:38.616 | info | Robocat instance successfully connected
ecovacs-deebot.0 | 2021-08-10 21:17:37.711 | info | Using device Device[0]
ecovacs-deebot.0 | 2021-08-10 21:17:37.710 | info | Device[0]:   {"did":"30e113b3-6737-4007-a5ea-2efb50e51823","name":"E0A412796B09HEZ50221","class":"yna5xi","resource":"Ja3s","nick":"Robocat","company":"eco-ng","bindTs":1609868337171,"service":{"jmq":"jmq-ngiot-eu.dc.ww.ecouser.net","mqs":"api-ngiot.dc-as.ww.ecouser.net"}}
ecovacs-deebot.0 | 2021-08-10 21:17:37.709 | info | Number of devices: 1
ecovacs-deebot.0 | 2021-08-10 21:17:37.702 | info | Successfully connected to Ecovacs server
ecovacs-deebot.0 | 2021-08-10 21:17:36.845 | info | starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v12.20.2, js-controller: 3.3.15
host.ioBkoker202 | 2021-08-10 21:17:34.484 | info | instance system.adapter.ecovacs-deebot.0 started with pid 337
host.ioBkoker202 | 2021-08-10 21:17:31.891 | info | instance system.adapter.ecovacs-deebot.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.ioBkoker202 | 2021-08-10 21:17:31.299 | info | stopInstance system.adapter.ecovacs-deebot.0 send kill signal
ecovacs-deebot.0 | 2021-08-10 21:17:31.190 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
ecovacs-deebot.0 | 2021-08-10 21:17:31.189 | info | terminating
ecovacs-deebot.0 | 2021-08-10 21:17:31.187 | info | cleaned everything up...
ecovacs-deebot.0 | 2021-08-10 21:17:31.181 | info | Got terminate signal TERMINATE_YOURSELF
host.ioBkoker202 | 2021-08-10 21:17:31.141 | info | stopInstance system.adapter.ecovacs-deebot.0 (force=false, process=true)


</body>
</html>

**Comment by mrbungle64** [comment]
@andre-bu 

Die Meldung `Request Timeout` (errorCode 500) kommt von der Ecovacs API und sagt vermutlich aus, dass diese einen Befehl (z.B. an den Bot) weitergeleitet hat und darauf keine Antwort mehr bekommen hat. Das ist nicht weiter schlimm, so lange es nicht über einen längeren Zeitraum im Sekunden- oder Minuten-Takt auftritt.

Diese Meldung war zwischendurch sogar mal unterdrückt, weil es nur genervt hat und in den meisten Fällen aber keine negativen Auswirkungen hatte. Da das aber auch nicht "im Sinne des Erfinders" ist habe ich das wieder geändert.

Heute gegen 16:25 Uhr sind die Meldungen dann im Zusammenhang mit dem eigentlichen Problem aufgetreten, dass die Ecovacs Server nicht erreichbar waren. Und zwar direkt am Anfang - vermutlich weil die Server da teilweise noch antworten konnten.

Im Endeffekt gilt ähnliches wie bei dem `RequestOAuthError: Authentication error`:
* Sollte es wenige Male am Tag auftreten: bitte vorerst ignorieren. Ich werde das versuchen weiter zu optiomieren
* Sollte es deutlich öfter und auch regelmäßig öfter als 3x am Tag auftreten bitte noch mal hier melden

Es ist halt leider weiterhin ein Problem, dass es keine öffentlich zugängliche Doku für die Ecovacs API gibt.
Und dass die Ecovacs API höchstwahrscheinlich gar nicht dafür konzipiert bzw. gedacht ist, dass sich Systeme wie ioBroker damit verbinden und man versucht eine 24/7 Verbindung aufrecht zu erhalten.
Der normale Anwendungsfall ist ja:
Ecovacs Mobile App wird geöffnet - Verbindung wird hergestellt - der User stellt ggf. irgendwas ein - schaut was nach - sendet ggf. einen Befehl - und schließt die App wieder (Verbindung wird ebenfalls beendet)
Und beim nächsten Mal wieder alles von vorne ...

**Comment by andre-bu** [comment]
Vielen Dank für diesen klasse Adapter. Schade das ECOVACS da so wenig
kooperiert. Der Adapter ist ein riesen Mehrwert für den Deebot. Danke auch
für deine Ausführliche Erklärung. Ich beobachte und werde berichten.

Sascha ***@***.***> schrieb am Di., 10. Aug. 2021, 22:38:

**Comment by Elektrickser** [comment]
Hi,

bei mir das gleiche mit dem Fehler "Request Timeout".

Die Meldung kommt immer im Aktualisierungsintervall. Hier mal die Meldungen von meinem Log, nach dem Neustart des Adapters:

`
ecovacs-deebot.0 | 2021-08-31 19:26:25.980 | warn | Error message received: Request Timeout

ecovacs-deebot.0 | 2021-08-31 19:25:25.992 | warn | Error message received: Request Timeout

ecovacs-deebot.0 | 2021-08-31 19:24:25.999 | warn | Error message received: Request Timeout

ecovacs-deebot.0 | 2021-08-31 19:23:31.990 | warn | Error message received: Request Timeout

ecovacs-deebot.0 | 2021-08-31 19:23:10.990 | info | [vacbot] name: DEEBOT OZMO 950 Series

ecovacs-deebot.0 | 2021-08-31 19:23:10.987 | info | BootBot instance successfully connected

ecovacs-deebot.0 | 2021-08-31 19:23:10.495 | info | Using device Device[0]

ecovacs-deebot.0 | 2021-08-31 19:23:10.494 | info | Device[0]:   
{"did":"7ba49dd6-0be0-4f53-8cc0-0fbbfd4d591c","name":"E0001279610062110867","class":"yna5xi","resource":"MyzO","nick":"BootBot","company":"eco-ng","bindTs":1591810773907,"service":{"jmq":"jmq-ngiot-eu.dc.ww.ecouser.net","mqs":"api-ngiot.dc-as.ww.ecouser.net"}}

ecovacs-deebot.0 | 2021-08-31 19:23:10.494 | info | Number of devices: 1

ecovacs-deebot.0 | 2021-08-31 19:23:10.493 | info | Successfully connected to Ecovacs server

ecovacs-deebot.0 | 2021-08-31 19:23:09.513 | info | starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v12.21.0, js-controller: 3.3.15

ecovacs-deebot.0 | 2021-08-31 19:23:04.660 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason

ecovacs-deebot.0 | 2021-08-31 19:23:04.658 | info | terminating

ecovacs-deebot.0 | 2021-08-31 19:23:04.658 | info | cleaned everything up...

ecovacs-deebot.0 | 2021-08-31 19:23:04.654 | info | Got terminate signal TERMINATE_YOURSELF

`

**Comment by mrbungle64** [comment]
@Elektrickser 

> Die Meldung kommt immer im Aktualisierungsintervall

Seit wann ist das so?

**Comment by andre-bu** [comment]
Hab gerade bei mir mal gecheckt. Mein LOG ist sauber. Adapter läuft und Deebot saugt.

**Comment by mrbungle64** [comment]
@Elektrickser 

Da ich bisher keine Antwort bekommen habe gehe ich mal davon aus, dass es sich hier ebenfalls um ein temporäres Problem gehandelt hat.

Ich greife aber noch mal das auf, was ich hier vor ca. 3 Wochen geschrieben hatte:

_"Die Meldung Request Timeout (errorCode 500) kommt von der Ecovacs API und sagt vermutlich aus, dass diese einen Befehl (z.B. an den Bot) weitergeleitet hat und darauf keine Antwort mehr bekommen hat. Das ist nicht weiter schlimm, so lange es nicht über einen längeren Zeitraum im Sekunden- oder Minuten-Takt auftritt."_

Daher die Frage seit wann das bei Dir auftritt.
Das würde ich mich auch weiterhin interessieren - und ob es immer noch auftritt.
Ich gehe aber trotzdem weiterhin erst mal von einem temporären Problem aus.

_"Diese Meldung war zwischendurch sogar mal unterdrückt, weil es nur genervt hat und in den meisten Fällen aber keine negativen Auswirkungen hatte. Da das aber auch nicht "im Sinne des Erfinders" ist habe ich das wieder geändert."_

Ich werde auch mal darüber nachdenken diese Meldung wieder zu unterdrücken (oder auf ein anderes Log Level zu packen) - nur dass man das diesmal in den Adapter Einstellungen ändern kann, wenn man ein "vollständiges" Log haben möchte.

**Comment by andre-bu** [comment]
Was die Karte und die Mobile App angeht kann ich das so bestätigen.

Sascha ***@***.***> schrieb am Mi., 1. Sept. 2021, 20:43:

**Comment by Elektrickser** [comment]
Also heute ist der Log im Iobroker sauber. Keinen `request timeout` mehr.

Jedoch hatte ich die Meldung 2x in der App als ich auf den Bot zugreifen wollte.
Ansonsten funktioniert aber alles.

**Comment by mrbungle64** [comment]
@Elektrickser @andre-bu @Pittini 

Danke für euer Feedback 👍🏻 

Ich werde allerdings den Issue jetzt schließen, da die gemeldeten Warnings im Log zwar alle nach dem Update auf 1.2.1 aufgetreten sind - aber trotzdem eigentlich nichts mit dem Update zu tun hatten.

Es sind ja im Endeffekt auch "nur" Warnings und keine Errors (obwohl die Ecovacs API einen Error meldet).
Der Adapter meldet im Log halt Errors der Ecovacs API - was aber eigentlich auch nur auffällt, weil der Adapter in einem 30-60 Sekunden Intervall Anfragen an die Ecovacs Server sendet. Dass das 100% fehlerfrei abläuft sollte man bei Consumer Produkten halt einfach nicht erwarten.

Wenn dann ein `Request Timeout` (oder auch `RequestOAuthError: Authentication error`) auftritt bekommt die nächste Anfrage (oder zumindest eine der nächsten) ja wieder erfolgreich eine Antwort - es sei denn es gibt Netzwerkprobleme, auf die der Adapter sowieso keinen Einfluss hat.
