### ISSUE TITLE
Installation bricht ab

### ISSUE THREAD

**Issue by manoloxxl** [mrbungle64/ioBroker.ecovacs-deebot#63]
Hi,
ich musste meine iObroker Instanz neu aufsetzen und bekomme seit dem den Adapter nicht mehr zum Laufen. Die Installation bricht mit dem Fehler ab:

Fertig mit Fehler: host.raspi-iobroker Cannot install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/0781744c3b3ef97ef6f84f0748c255c19aa2eb02: 1

Das Log:
```
$ ./iobroker url "https://github.com/mrbungle64/ioBroker.ecovacs-deebot"
install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/0781744c3b3ef97ef6f84f0748c255c19aa2eb02
NPM version: 6.14.4
npm install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/0781744c3b3ef97ef6f84f0748c255c19aa2eb02 --loglevel error --prefix "/opt/iobroker" (System call)
Package pixman-1 was not found in the pkg-config search path.Perhaps you should add the directory containing `pixman-1.pc'to the PKG_CONFIG_PATH environment variableNo package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack
 Error: `gyp` failed with exit code: 1gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)gyp ERR! stack     at ChildProcess.emit (events.js:310:20)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)gyp
 ERR! System Linux 4.19.97-v7l+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/iobroker/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"gyp ERR! cwd /opt/iobroker/node_modules/canvasgyp ERR! node -v v12.16.3gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/iobroker/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/iobroker/node_modules/canvas/node_modules/node-pre-gyp/lib/util/compile.js:83:29)node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.19.97-v7l+node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"node-pre-gyp ERR! cwd /opt/iobroker/node_modules/canvasnode-pre-gyp ERR! node -v v12.16.3node-pre-gyp ERR! node-pre-gyp -v v0.11.0node-pre-gyp ERR! not ok 
npm
 ERR! 
code
 ELIFECYCLE
npm
 ERR! errno 1npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`npm ERR! Exit status 1npm ERR! npm 
ERR! Failed at the canvas@2.6.1 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-04-29T21_29_46_512Z-debug.log
ERROR: host.raspi-iobroker Cannot install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/0781744c3b3ef97ef6f84f0748c255c19aa2eb02: 1
ERROR: process exited with code 25
```

Vermutlich muss ich GYP oder CANVAS installieren, habe nun einuge Zeit gegoogelt, finde aber nichts weiter dazu. Und bin ich Linux leider (noch) relativ unfähig.

Hat jemand einen Tipp was ich machen muss?

Grüße

Manuel

**Comment by mrbungle64** [comment]
Hallo @manoloxxl 

hast Du die Installations-Anleitung soweit befolgt?
https://github.com/mrbungle64/ioBroker.ecovacs-deebot#Installation

**Comment by manoloxxl** [comment]
Hi,

selbstverständlich nicht - sorry.

Danke! Läuft jetzt natürlich ;)

Grüße

Manuel
